[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.125.4"
  HUGO_ENV = "production"

[context.production]
  command = "hugo --gc --minify --baseURL $URL"

[context.deploy-preview]
  command = "hugo --gc --minify --baseURL $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify --baseURL $DEPLOY_PRIME_URL"